### ISSUE TITLE
`mouseleave` handler is needed

### ISSUE THREAD

**Issue by msimpson** [egraether/mine3D#3]
There doesn't appear to be a `mouseleave` handler in regard to the view controls so they become sticky if the mouse leaves the window during dragging.

Related to #2

**Comment by jnm2** [comment]
@egraether merged #2 and published it to the website. This seems to fix everything for me, is there anything else that needs to be done?

**Comment by msimpson** [comment]
@jnm2 
This fixed it for me.

**Comment by jnm2** [comment]
Great!
Maybe you should close this issue?
